
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}


#logging:
 # pattern:
  #  console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId},%X{spanId}] %-5level %logger - %msg%n"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  override-with-generic-response: false

  default-produces-media-type: application/json
  default-consumes-media-type: application/json

