
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  override-with-generic-response: false

  default-produces-media-type: application/json
  default-consumes-media-type: application/json

